from turtle import *
canvas = Screen()
canvas.setup(800, 600)
madonna = Turtle()
madonna.shape("turtle")
madonna.color("red")
madonna.penup()
madonna.goto(-250,0)
madonna.pendown()
madonna.left(75)
madonna.forward(100)
madonna.right(150)
madonna.forward(100)
madonna.backward(50)
madonna.left(75)
madonna.backward(25)
madonna.penup()
madonna.goto(-180,55)
madonna.pendown()
madonna.right(90)
madonna.forward(55)
madonna.backward(40)
madonna.left(90)
madonna.forward(35)
madonna.right(90)
madonna.forward(40)
madonna.penup()
madonna.goto(-125,0)
madonna.pendown()
madonna.right(180)
madonna.forward(90)
madonna.backward(30)
madonna.right(90)
madonna.forward(25)
madonna.backward(50)
madonna.penup()
madonna.goto(-100,0)
madonna.pendown()
madonna.left(90)
madonna.forward(90)
madonna.backward(50)
madonna.right(90)
madonna.forward(35)
madonna.right(90)
madonna.forward(40)
madonna.penup()
madonna.goto(-50,0)
madonna.pendown()
madonna.backward(40)
madonna.left(90)
madonna.forward(40)
madonna.right(90)
madonna.forward(40)
madonna.right(90)
madonna.forward(40)
madonna.penup()
madonna.goto(10,0)
madonna.pendown()
madonna.right(90)
madonna.forward(55)
madonna.backward(15)
madonna.right(90)
madonna.forward(35)
madonna.right(90)
madonna.forward(40)
madonna.penup()
madonna.goto(70,0)
madonna.pendown()
madonna.backward(40)
madonna.forward(40)
madonna.left(90)
madonna.forward(40)
madonna.left(90)
madonna.forward(40)
madonna.backward(80)
madonna.left(90)
madonna.forward(40)








