from turtle import * 
canvas = Screen()
canvas.setup(800,600)
xavier = Turtle()
xavier.shape("turtle")
xavier.color("red")

xavier.goto(0,0)
xavier.right(-70)
xavier.forward(60)
xavier.goto(0,0)
xavier.left(70)
xavier.forward(60)
xavier.goto(0,0)
xavier.left(-190)
xavier.forward(60)
xavier.goto(0,0)
xavier.right(70)
xavier.forward(60)
#letter x

xavier.goto(0,0)
xavier.penup()
xavier.right(-130)
xavier.forward(40)
xavier.pendown()
xavier.right(300)
xavier.forward(90)
xavier.right(120)
xavier.forward(90)
xavier.right(-175)
xavier.penup()
xavier.forward(40)
xavier.left(60)
xavier.pendown()
xavier.forward(50)
#letter A
