from turtle import *
canvas = Screen()
canvas.setup(800,600)
stitch = Turtle()
stitch.shape("turtle")
stitch.color("red")
stitch.circle(60)
stitch.forward(80)
stitch.left(90)
stitch.forward(100)
stitch.backward(200)
stitch.forward(100)
stitch.right(30)
stitch.forward(40)
stitch.right(60)
stitch.forward(30)
stitch.right(90)
stitch.forward(125)
stitch.left(90)
stitch.forward(40)
stitch.left(90)
stitch.forward(100)
stitch.right(30)
stitch.forward(20)
